### ISSUE TITLE
"add_inputs" not working

### ISSUE THREAD

**Issue by RuneJunker** [phillipbvetter/ctsmrTMB#1]
When adding an input as stated in the documentation I get the following error:
"Error in `stringr::str_match()`:
! `string` must be a vector, not a symbol.
Run `rlang::last_error()` to see where the error occurred."
When running "rlang::last_error()" as suggested by the error I get:
"Error in `stringr::str_match()`:
! `string` must be a vector, not a symbol.

Backtrace:
 1. obj$add_inputs(u)
 2. base::lapply(...)
 3. ctsmrTMB (local) FUN(X[[i]], ...)
 4. ctsmrTMB:::check_inputs(args, self, private)
 5. stringr::str_match(input, "^(?!d[tw])[[:alnum:]]*")"
 
The following is a minimal example:
obj = ctsmrTMB$new()

obj$set_modelname("CLPS")
obj$add_systems(
  dx1 ~ 1/C1*((                  1/R12 * (x2-x1) + Rcable * u^2)* dt+ sigma_x * dw1)
)
obj$add_inputs(u)

**Comment by phillipbvetter** [comment]
I have been using an older version of stringr. I will update the code asap.

**Comment by phillipbvetter** [comment]
I have fixed this now. I expect some more errors might arise due to the apparent changes in stringr, but haven't been able to identify others. Let me know if you encounter a similar error.
