### ISSUE TITLE
A concise format for parameters initial values

### ISSUE THREAD

**Issue by pederbacher** [phillipbvetter/ctsmrTMB#10]
### Estimates all parameters
obj$add_parameters(
Ci =5 ,-Inf ,Inf,
Ria=5 ,0.1 ,100,
gA =20 ,-Inf ,Inf
)

### and this will work too
obj$add_parameters(
Ci =5 ,lb=-Inf ,ub=Inf,
Ria=5 ,lb=0.1 ,ub=100,
gA =20 ,lb=-Inf ,ub=Inf
)

### If limits are not given, it doesn't estimate Ci, but set it fixed to 5
obj$add_parameters(
Ci =5 ,#,-Inf ,Inf,
Ria=5 ,-Inf ,Inf,
gA =20 ,-Inf ,Inf
)

**Comment by phillipbvetter** [comment]
This looks to me like what we have in the current implementation. But you must wrap the three-wise elements in c() so the three cases are

```r
obj$add_parameters(
Ci = c(5,-Inf,Inf),
Ria = c(5,0.1,100),
gA = c(20,-Inf,Inf),
)
```


```r
obj$add_parameters(
Ci = 5,
Ria = c(5,-Inf,Inf)
gA = c(20,-Inf,Inf)
)
```

**Comment by pederbacher** [comment]
Yes, maybe it was just to get rid of the c()...seen it too much in my life ;D
