### ISSUE TITLE
Explain predict functionality in help

### ISSUE THREAD

**Issue by pederbacher** [phillipbvetter/ctsmrTMB#11]
write this in the help of $predict():
Ja den kører bare kalman filteret, men så er der lige et ekstra for-loop der fremskriver ODE ligningerne fra seq(i , i + k.step.ahead) gange som du siger, og gemmer resultaterne, og så gemmer vi bare 1.step (i+1) fremskrivningen, opdatere state, kører forfra...

**Comment by pederbacher** [comment]
and that the returned zero horizon (k==0) values are the filter updates, right?

**Comment by phillipbvetter** [comment]
Yes that’s correct.

Mvh
Phillip
________________________________

**Comment by pederbacher** [comment]
These would be good to have in the documentation and a vignette...I can try to work out some draft vignettes?
