### ISSUE TITLE
fit$residuals$sd is now variance, not standard error

### ISSUE THREAD

**Issue by pederbacher** [phillipbvetter/ctsmrTMB#12]
Yo...

In a model I have it's quite clear that if I take the sqrt() to the fit$residuals$sd then it fits the way it should...so I guess that it's a simple mistake, also the standardized residuals are not correct now...

I think...can you check @phillipbvetter ?

:D

**Comment by phillipbvetter** [comment]
Whoops - fixed now.

Thanks for that 👍

**Comment by pederbacher** [comment]
Yes, confirmed :)
