### ISSUE TITLE
Names on return from predict

### ISSUE THREAD

**Issue by pederbacher** [phillipbvetter/ctsmrTMB#13]
1) Hmm, the names in the returned data.frame use R code syntas, like "+", "{", "["...:
k+i  t_{k} t_{k+i} k.step.ahead       Ti       Tw      var[Ti]

it would be good to avoid (also avoid space " ")...

I guess "." is ok as a separator...

2) hmm, now "k" and "i" are counters for indexing...It's a bit of a legacy from ctsm to use "k" as index t_k. I really don't know why it shouldn't be "i" !? and then use "k" added to that "i+k" so "k" is the horizon, that's how it is used in Henriks time series book...

**Comment by phillipbvetter** [comment]
I changed the names, and reversed index i and k. I agree, since we're already using k in k.step.ahead :-)

**Comment by phillipbvetter** [comment]
See update please

**Comment by pederbacher** [comment]
Yes...back again...;D

hmm, I see it, then "t.k" is nice...but I do like "k" being "n.ahead" and then not have the current k (it's easy and logic to calculate)...I can't come up with a good name for t.k then...

This one use k as the horizon, I have kept that notation in forecasting:
https://journals.sagepub.com/doi/pdf/10.1260/030952405776234599?casa_token=weWmoqFyuI4AAAAA:XXzV4z6OqNv39-a6O2vjQx96OOHFS9XpAjnGFgsz8ZRanPPM9AvHBB8e8-bi27lmzIVQPj20OIA

Args, "n.ahead" is for me like a "max" k-horizon...

bong bong bong

**Comment by pederbacher** [comment]
så denne her:
i j t.i t.j k.ahead
