### ISSUE TITLE
k.step.ahead in predict()

### ISSUE THREAD

**Issue by pederbacher** [phillipbvetter/ctsmrTMB#16]
In Arima it's "n.ahead":
```r
> stats:::predict.Arima
function (object, n.ahead = 1L, newxreg = NULL, se.fit = TRUE, 
```

Why not simply call it "k"? and then consistenly use "i" as index and "k" as horizon?

**Comment by phillipbvetter** [comment]
We could also use n.ahead? Please see updated names

**Comment by pederbacher** [comment]
hmm...yes, here can work...but somehow would like "k" consistently as horizon...
