### ISSUE TITLE
Export predict function

### ISSUE THREAD

**Issue by pederbacher** [phillipbvetter/ctsmrTMB#3]
It's a bit annoying, but I know no other way, than exporting the predict.ctsmrTMB.fit function, otherwise it can't be seen and the help can't be called, now one has to do "ctsmrTMB:::predict.ctsmrTMB.fit" to see it...

**Comment by phillipbvetter** [comment]
This is "fixed" with the implementation of the new prediction function I guess?

You can find the documentation with `?ctsmrTMB` under `:predict()`
