### ISSUE TITLE
Enable prediction with an unestimated model

### ISSUE THREAD

**Issue by pederbacher** [phillipbvetter/ctsmrTMB#4]
Now one has to pass the fit to the predict function, but it is very useful to be able to do predict before estimating, with the initial parameter values...it's the best way to get started checking if the model and initial parameters are reasonable set.

We should write a nice vignette on "tips to getting started on a new model"...

**Comment by phillipbvetter** [comment]
This is now implemented for the ``èkf```

**Comment by phillipbvetter** [comment]
These should be fixed now - I can run your script on my side. Please try again.

**Comment by pederbacher** [comment]
Thanks man! Somehow, weirdly, I had the error a few times testing now, then it disappeared, can't explain it...now it works :)
