### ISSUE TITLE
Is running without upper and lower bound in nlminb possible?

### ISSUE THREAD

**Issue by pederbacher** [phillipbvetter/ctsmrTMB#5]
Right now I can't find a way with estimate() to not use lower and upper bounds on parameters, are there anything in the way for not using bounds?

**Comment by phillipbvetter** [comment]
You can use e.g.

```r
obj$add_parameters(
fake_parameter ~ c(init = 0, lower = -Inf, upper = Inf)
)
```

**Comment by pederbacher** [comment]
Great! of course! I have added it to a list I keep of things to be mentioned in vignettes (just all the things I ask about, then others probably have that question too)...

Ideas for making opt parameter definitions more concise...is it now possible to fix a parameter in the model? (as suggested below). I was wondering why use '~' as it's done now?

A concise format:

# Estimates all parameters
obj$add_parameters(
        Ci =5   ,-Inf  ,Inf,
        Ria=5   ,0.1   ,100,
        gA =20 ,-Inf  ,Inf
       )
# and this will work too
obj$add_parameters(
        Ci =5    ,lb=-Inf  ,ub=Inf,
        Ria=5   ,lb=0.1   ,ub=100,
        gA =20 ,lb=-Inf  ,ub=Inf
       )

# If limits are not given, it doesn't estimate Ci, but set it fixed to 5
obj$add_parameters(
        Ci =5    ,#,-Inf  ,Inf,
        Ria=5   ,-Inf  ,Inf,
        gA =20 ,-Inf  ,Inf
)

**Comment by phillipbvetter** [comment]
Yes, fixing a parameter is already possible in the way you suggest, or by explicitly setting lower and upper bound to NA.

**Comment by phillipbvetter** [comment]
Could try to change from `~` to `=`, it was just easier to implement like that for me...

**Comment by phillipbvetter** [comment]
This is now implemented

**Comment by pederbacher** [comment]
Great! A shorter format can always be added...so closing this one now.
