### ISSUE TITLE
Get the parameters with an "obj$get_parameters()" function

### ISSUE THREAD

**Issue by pederbacher** [phillipbvetter/ctsmrTMB#6]
It should return the matrix format which can also be given to get_parameters()

Alternatively, access to the private fields with such varables, but guess that is a bit against the OOP princilpes...

- One other quick thing: Could this be made such that when class of prm is matrix, then it takes it automatically? ie. not needing to write "parameter.matrix": obj$add_parameters(parameter.matrix=prm)

**Comment by phillipbvetter** [comment]
get_parameters is implemented, and your quick thing suggestion to add_parameters as also implemented.

**Comment by pederbacher** [comment]
Great :) 

> obj$get_parameters()
            Type Initial Lower Bound Upper Bound
Ci          free       5        -Inf         Inf

Hmm, could the columns names be: "type", "init", "lb", "ub", i.e. the same as in add_parameters()?

and as a matrix I guess, in order to give it back to add_parameters()
prm <- obj$get_parameters()
> obj$add_parameters(prm)
Error in FUN(X[[i]], ...) : 
  You can only supply parameter vectors or matrices

**Comment by phillipbvetter** [comment]
This is implemented now, but requires that the provided data.frame or matrix to `add_parameters` has column names called "init", "lb", "ub", i.e. that this returns `TRUE`

```r
all(c("init","lb","ub") %in% colnames(prm))

```

**Comment by pederbacher** [comment]
Super duper! maybe "lower" and "upper" is better than "lb" and "ub", I think now, since that is what they are called in nlminb, so more intuitive...yeah

**Comment by phillipbvetter** [comment]
Agreed. Will change to "initial", "lower" and "upper"
