### ISSUE TITLE
get functions

### ISSUE THREAD

**Issue by pederbacher** [phillipbvetter/ctsmrTMB#7]
Some different "get functions", like:
$get_parameters()
both somehow should give the parameters with set inital values opt. boundaries, but also all the identified parameters in the model, i.e. give the matrix form, with NAs for the parameters not set.

$get_states() 
get the states and potential set init values and cov.

...or maybe a get function for each set function is actually needed?

**Comment by pederbacher** [comment]
kan du lave nogle andre "get" funktioner....jeg har mange modeller og vil gerne sætte init parametre et sted, men for kun at sætte de parametre, som er i modellen, så skal jeg vide hvilke parametre den model har...altså i kode.

I cannot add non-existing parameters (error from $estimate()):
```r
library(ctsmrTMB)
obj = ctsmrTMB$new()
obj$add_systems(
        dTi ~ ( 1/(Ci*Ria)*(Ta-Ti) + gA/Ci*Ps + 1/Ci*Ph )*dt + sigmaTi*dw1
)
obj$add_observations(
  YTi ~ Ti
)
obj$add_observation_variances(
  YTi ~ sigmaYTi^2
)
obj$add_algebraics(
  sigmaTi ~ exp(logsigmaTi),
  sigmaYTi ~ exp(logsigmaYTi)
)

# Add a non-existing parameter, can it throw an error immediately, since not a parameter in the model
obj$add_parameters(
        Ce =  c(init=5   ,lb=1E-2  ,ub=200 )
    )

# Get the parameters, even though their initial values were not set. Is that possible before compiling?
# Should always return all the the parameters in the model!? (and not some not in the model)
obj$get_parameters()

´´´

**Comment by phillipbvetter** [comment]
I added this feature:

# Add a non-existing parameter, can it throw an error immediately, since not a parameter in the mode

**Comment by pederbacher** [comment]
Great! 

Then some get functions...to for all "add" functions, there should be get functions...
