### ISSUE TITLE
Vignette showing how extract the objective function etc. and use other optimizer.

### ISSUE THREAD

**Issue by pederbacher** [phillipbvetter/ctsmrTMB#9]
Just to remember, since it's not in the help file...and I guess needs more explanaition than nice to put in help file...

**Comment by phillipbvetter** [comment]
I have started with that here

https://phillipbvetter.github.io/ctsmrTMB/articles/construct_nll.html

**Comment by pederbacher** [comment]
Great, let me know how to contribute...
